name: Triage Copilot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  triage:
    name: Triage and Dispatch
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.draft == false &&
      (
        contains(github.event.pull_request.user.login, 'copilot') ||
        contains(github.event.pull_request.user.login, 'github-actions')
      )

    steps:
      - name: Trigger CI Workflow
        run: |
          gh workflow run build-and-publish.yml --ref ${{ github.event.pull_request.head.ref }} -f pr_number=${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}